/**
 * Operator API client: fetch wrapper + RFC 7807 Problem parsing.
 *
 * Typed request/response shapes come from src/api/generated/ (checked in,
 * regenerated by a scheduled CI job — design §3.3).
 */

/** RFC 7807 problem details, as the operator emits them. */
export interface Problem {
  type?: string;
  title?: string;
  status?: number;
  detail?: string;
  instance?: string;
}

export class ApiError extends Error {
  constructor(
    readonly problem: Problem,
    readonly httpStatus: number,
  ) {
    super(problem.title ?? `Operator API error (HTTP ${httpStatus})`);
    this.name = "ApiError";
  }
}

export class ApiClient {
  // TODO(SPEC-057 T6-06): consumed once request() is implemented.
  constructor(
    protected readonly baseUrl: string,
    protected readonly getToken: () => Promise<string>,
  ) {}

  /**
   * TODO(SPEC-057 T6-06): implement fetch with bearer auth, timeout from
   * `airdress.requestTimeoutMs`, optional `x-airdress-trace: 1`, and
   * application/problem+json parsing into ApiError.
   */
  async request<T>(_path: string, _init?: RequestInit): Promise<T> {
    throw new Error("TODO(SPEC-057 T6-06): API client not implemented");
  }
}
